import { RepositoryService } from './repository.service.js';
import { AuditService } from './audit.service.js';

export interface GitBranchInfo {
  repository: string;
  currentBranch: string;
  branches: string[];
}

export interface GitStatusResult {
  repository: string;
  branch: string;
  stagedFiles: string[];
  modifiedFiles: string[];
  untrackedFiles: string[];
  isClean: boolean;
}

export interface PullRequestResult {
  repository: string;
  prNumber: number;
  title: string;
  sourceBranch: string;
  targetBranch: string;
  prUrl: string;
  status: 'open' | 'draft';
  summary: string;
}

export class GitService {
  private static instance: GitService;
  private auditService: AuditService;
  private repoService: RepositoryService;

  // In-memory branch and PR tracking for mock/local git ops
  private branchState: Map<string, { current: string; branches: Set<string> }> = new Map();
  private prCounter: number = 100;

  private constructor() {
    this.auditService = AuditService.getInstance();
    this.repoService = RepositoryService.getInstance();
  }

  public static getInstance(): GitService {
    if (!GitService.instance) {
      GitService.instance = new GitService();
    }
    return GitService.instance;
  }

  private getOrCreateRepoGit(repoName: string) {
    if (!this.branchState.has(repoName.toLowerCase())) {
      this.branchState.set(repoName.toLowerCase(), {
        current: 'main',
        branches: new Set(['main', 'develop'])
      });
    }
    return this.branchState.get(repoName.toLowerCase())!;
  }

  public createBranch(repoName: string, branchName: string): { success: boolean; branch: string; repository: string } {
    const git = this.getOrCreateRepoGit(repoName);
    git.branches.add(branchName);
    git.current = branchName;

    this.auditService.log({
      actor: 'codex',
      action: 'create_branch',
      repository: repoName,
      status: 'success',
      details: { branchName }
    });

    return {
      success: true,
      branch: branchName,
      repository: repoName
    };
  }

  public getStatus(repoName: string): GitStatusResult {
    const git = this.getOrCreateRepoGit(repoName);
    // Return standard branch info
    return {
      repository: repoName,
      branch: git.current,
      stagedFiles: [],
      modifiedFiles: ['src/config/app.config.ts', 'package.json'],
      untrackedFiles: [],
      isClean: false
    };
  }

  public getDiff(repoName: string, options?: { staged?: boolean }): { repository: string; diff: string } {
    const git = this.getOrCreateRepoGit(repoName);
    const mockDiff = `diff --git a/src/config/app.config.ts b/src/config/app.config.ts\n--- a/src/config/app.config.ts\n+++ b/src/config/app.config.ts\n@@ -0,0 +1,10 @@\n+// Generated by NSTOK AI Software Factory\n+export const AppConfig = {\n+  name: '${repoName}',\n+  status: 'active'\n+};\n`;

    return {
      repository: repoName,
      diff: mockDiff
    };
  }

  public createCommit(
    repoName: string,
    message: string,
    files?: string[]
  ): { success: boolean; commitHash: string; branch: string; message: string } {
    const git = this.getOrCreateRepoGit(repoName);
    const commitHash = `c_${Date.now().toString(16)}`;

    this.auditService.log({
      actor: 'codex',
      action: 'create_commit',
      repository: repoName,
      status: 'success',
      details: { commitHash, branch: git.current, message, files }
    });

    return {
      success: true,
      commitHash,
      branch: git.current,
      message
    };
  }

  public createPullRequest(
    repoName: string,
    title: string,
    body: string,
    targetBranch: string = 'main'
  ): PullRequestResult {
    const git = this.getOrCreateRepoGit(repoName);
    const prNumber = ++this.prCounter;
    const sourceBranch = git.current;

    this.auditService.log({
      actor: 'codex',
      action: 'create_pull_request',
      repository: repoName,
      status: 'success',
      details: { prNumber, title, sourceBranch, targetBranch }
    });

    return {
      repository: repoName,
      prNumber,
      title,
      sourceBranch,
      targetBranch,
      prUrl: `https://github.com/nstok-org/${repoName}/pull/${prNumber}`,
      status: 'open',
      summary: body
    };
  }
}
